"""init tenant and user

Revision ID: 0001_init_tenant_and_user
Revises:
Create Date: 2026-04-25 00:00:00.000000

Hand-written migration (not autogenerated) because we need:
  - pgcrypto extension for gen_random_uuid()
  - Postgres ENUM types before table creation
  - Row-Level Security on the users table

RLS NOTE for backend-dev
------------------------
Before any tenant-scoped query execute:

    SET LOCAL app.tenant_id = '<uuid>';

Best done in a SQLAlchemy after_begin event listener on the AsyncSession, or
in the get_db dependency after yielding the session.  The 'fh' DB role owns
the table and bypasses RLS automatically (Postgres owner bypass).
Admin queries that must cross tenants: SET LOCAL row_security = off;
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_init_tenant_and_user"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # ------------------------------------------------------------------
    # 1. Extensions
    # ------------------------------------------------------------------
    conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))

    # ------------------------------------------------------------------
    # 2. Enum types — created via raw SQL so they land in the transaction.
    # ------------------------------------------------------------------
    conn.execute(sa.text(
        "CREATE TYPE tenant_status AS ENUM "
        "('pending_approval', 'active', 'suspended')"
    ))
    conn.execute(sa.text(
        "CREATE TYPE platform_role AS ENUM "
        "('super_admin', 'operations_admin', 'finance_admin')"
    ))
    conn.execute(sa.text(
        "CREATE TYPE tenant_role AS ENUM "
        "('company_owner', 'company_admin', 'property_admin', "
        "'listing_manager', 'agent', 'finance_user', 'read_only')"
    ))
    conn.execute(sa.text(
        "CREATE TYPE user_status AS ENUM ('active', 'disabled')"
    ))

    # ------------------------------------------------------------------
    # 3. tenants
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE tenants (
            id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
            name        VARCHAR(255) NOT NULL,
            slug        VARCHAR(100) NOT NULL,
            status      tenant_status NOT NULL DEFAULT 'pending_approval',
            currency    VARCHAR(10)  NOT NULL DEFAULT 'AED',
            timezone    VARCHAR(64)  NOT NULL DEFAULT 'Asia/Dubai',
            locale      VARCHAR(10)  NOT NULL DEFAULT 'en',
            approved_at TIMESTAMPTZ,
            approved_by_id UUID,
            created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
        )
    """))
    conn.execute(sa.text(
        "CREATE UNIQUE INDEX uq_tenants_slug ON tenants (slug)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX ix_tenants_slug ON tenants (slug)"
    ))

    # ------------------------------------------------------------------
    # 4. platform_users (cross-tenant, no tenant_id)
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE platform_users (
            id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
            email          VARCHAR(255)  NOT NULL,
            password_hash  VARCHAR(255)  NOT NULL,
            full_name      VARCHAR(255)  NOT NULL,
            role           platform_role NOT NULL,
            status         user_status   NOT NULL DEFAULT 'active',
            email_verified BOOLEAN       NOT NULL DEFAULT false,
            last_login_at  TIMESTAMPTZ,
            created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
            updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
        )
    """))
    conn.execute(sa.text(
        "CREATE UNIQUE INDEX uq_platform_users_email "
        "ON platform_users (email)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX ix_platform_users_email ON platform_users (email)"
    ))

    # ------------------------------------------------------------------
    # 5. users (tenant-scoped)
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE users (
            id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id      UUID          NOT NULL
                               REFERENCES tenants(id) ON DELETE CASCADE,
            email          VARCHAR(255)  NOT NULL,
            password_hash  VARCHAR(255)  NOT NULL,
            full_name      VARCHAR(255)  NOT NULL,
            role           tenant_role   NOT NULL,
            status         user_status   NOT NULL DEFAULT 'active',
            email_verified BOOLEAN       NOT NULL DEFAULT false,
            last_login_at  TIMESTAMPTZ,
            phone          VARCHAR(50),
            created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
            updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
        )
    """))
    conn.execute(sa.text(
        "CREATE INDEX ix_users_tenant_id ON users (tenant_id)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX ix_users_email ON users (email)"
    ))
    conn.execute(sa.text(
        "CREATE UNIQUE INDEX uq_users_tenant_email "
        "ON users (tenant_id, email)"
    ))

    # ------------------------------------------------------------------
    # 6. Row-Level Security on users
    #
    # The 'fh' DB role owns the table and bypasses RLS automatically.
    # Application sessions must: SET LOCAL app.tenant_id = '<uuid>';
    # ------------------------------------------------------------------
    conn.execute(sa.text("ALTER TABLE users ENABLE ROW LEVEL SECURITY"))
    conn.execute(sa.text("""
        CREATE POLICY tenant_isolation ON users
            USING (
                tenant_id = current_setting('app.tenant_id', true)::uuid
            )
            WITH CHECK (
                tenant_id = current_setting('app.tenant_id', true)::uuid
            )
    """))

    # Track the migration in alembic_version (Alembic does this automatically
    # via context, but raw conn.execute DDL won't interfere).


def downgrade() -> None:
    conn = op.get_bind()

    conn.execute(sa.text(
        "DROP POLICY IF EXISTS tenant_isolation ON users"
    ))
    conn.execute(sa.text(
        "ALTER TABLE users DISABLE ROW LEVEL SECURITY"
    ))
    conn.execute(sa.text("DROP TABLE IF EXISTS users"))
    conn.execute(sa.text("DROP TABLE IF EXISTS platform_users"))
    conn.execute(sa.text("DROP TABLE IF EXISTS tenants"))

    conn.execute(sa.text("DROP TYPE IF EXISTS user_status"))
    conn.execute(sa.text("DROP TYPE IF EXISTS tenant_role"))
    conn.execute(sa.text("DROP TYPE IF EXISTS platform_role"))
    conn.execute(sa.text("DROP TYPE IF EXISTS tenant_status"))

    conn.execute(sa.text("DROP EXTENSION IF EXISTS pgcrypto"))
