"""audit_log

Revision ID: 0002_audit_log
Revises: 0001_init_tenant_and_user
Create Date: 2026-04-25 00:00:01.000000

Hand-written migration (not autogenerated) because:
  - Custom Postgres enum type must be created before the table.
  - RLS policy and composite indexes need explicit DDL.

RLS behaviour on audit_logs:
  Tenant sessions (app.tenant_id is set) see:
    - rows belonging to their tenant  (tenant_id = app.tenant_id)
    - platform-generated rows         (tenant_id IS NULL)
  Platform-admin sessions (app.tenant_id not set, GUC missing):
    current_setting('app.tenant_id', true) returns NULL when the GUC is absent.
    NULL = NULL is FALSE in SQL, so the second predicate never matches.
    The IS NULL branch still passes → platform admins see only NULL-tenant rows.
    That is intentional: cross-tenant admin views use the DB owner role, which
    bypasses RLS automatically.

Adding new AuditAction values later:
  1. Add the member to enums.AuditAction (Python).
  2. In a new migration: ALTER TYPE audit_action ADD VALUE 'new_value';
     Note: ALTER TYPE ADD VALUE cannot run inside a transaction block on PG<13.
     On PG 16 (our target) it can. Use op.execute() inside upgrade().
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_audit_log"
down_revision: Union[str, None] = "0001_init_tenant_and_user"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# All values must match AuditAction enum members' .value strings exactly.
_AUDIT_ACTION_VALUES = (
    "tenant_created",
    "tenant_approved",
    "tenant_suspended",
    "tenant_updated",
    "user_created",
    "user_role_changed",
    "user_disabled",
    "user_password_changed",
    "document_accessed",
    "document_uploaded",
    "commission_overridden",
    "deal_stage_changed",
    "agent_commission_changed",
    "payment_link_state_changed",
    "login_succeeded",
    "login_failed",
    "other",
)


def upgrade() -> None:
    conn = op.get_bind()

    # ------------------------------------------------------------------
    # 1. Enum type
    # ------------------------------------------------------------------
    values_sql = ", ".join(f"'{v}'" for v in _AUDIT_ACTION_VALUES)
    conn.execute(sa.text(
        f"CREATE TYPE audit_action AS ENUM ({values_sql})"
    ))

    # ------------------------------------------------------------------
    # 2. audit_logs table
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE audit_logs (
            id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

            -- Nullable: platform-level events have no tenant owner.
            tenant_id             UUID         REFERENCES tenants(id)
                                               ON DELETE SET NULL,

            -- Actor: tenant user XOR platform operator; both NULL = system.
            actor_user_id         UUID         REFERENCES users(id)
                                               ON DELETE SET NULL,
            actor_platform_user_id UUID        REFERENCES platform_users(id)
                                               ON DELETE SET NULL,

            action                audit_action NOT NULL,

            -- Target entity (loosely typed to stay domain-agnostic).
            entity_type           VARCHAR(64),
            entity_id             UUID,

            -- State snapshots — store changed fields only, never credentials.
            metadata_before       JSONB,
            metadata_after        JSONB,

            -- Request context.
            ip_address            INET,
            user_agent            VARCHAR(512),

            -- Immutable: no updated_at.
            created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
        )
    """))

    # ------------------------------------------------------------------
    # 3. Indexes
    # ------------------------------------------------------------------

    # Primary read path: recent audit trail for a tenant.
    conn.execute(sa.text(
        "CREATE INDEX ix_audit_logs_tenant_created "
        "ON audit_logs (tenant_id, created_at DESC)"
    ))

    # History of a specific record (e.g. all changes to deal abc-123).
    conn.execute(sa.text(
        "CREATE INDEX ix_audit_logs_entity "
        "ON audit_logs (entity_type, entity_id, created_at DESC)"
    ))

    # Actor history — tenant user.
    conn.execute(sa.text(
        "CREATE INDEX ix_audit_logs_actor_user "
        "ON audit_logs (actor_user_id, created_at DESC)"
    ))

    # Actor history — platform operator.
    conn.execute(sa.text(
        "CREATE INDEX ix_audit_logs_actor_platform_user "
        "ON audit_logs (actor_platform_user_id, created_at DESC)"
    ))

    # ------------------------------------------------------------------
    # 4. Row-Level Security
    #
    # Policy logic (see module docstring for full explanation):
    #   tenant_id IS NULL   → always visible (platform-generated event)
    #   tenant_id = GUC     → visible to matching tenant session
    #   GUC missing         → current_setting(..., true) returns NULL;
    #                         NULL = anything is FALSE, so only IS NULL rows
    #                         pass — correct for platform-admin sessions.
    # ------------------------------------------------------------------
    conn.execute(sa.text("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY"))
    conn.execute(sa.text("""
        CREATE POLICY tenant_isolation ON audit_logs
            USING (
                tenant_id IS NULL
                OR tenant_id = current_setting('app.tenant_id', true)::uuid
            )
    """))
    # No WITH CHECK clause: audit rows are inserted by trusted server code
    # that always supplies the correct tenant_id (or NULL for platform events).
    # Restricting inserts via RLS would block legitimate NULL-tenant writes.


def downgrade() -> None:
    conn = op.get_bind()

    conn.execute(sa.text(
        "DROP POLICY IF EXISTS tenant_isolation ON audit_logs"
    ))
    conn.execute(sa.text(
        "ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY"
    ))
    conn.execute(sa.text("DROP TABLE IF EXISTS audit_logs"))
    conn.execute(sa.text("DROP TYPE IF EXISTS audit_action"))
