"""DocumentRequest model — tokenized customer document collection.

Flow (PRD §12):
  1. Agent creates a DocumentRequest for a customer (optional lead/deal link).
  2. System generates a URL-safe token; agent shares URL out-of-band.
  3. Agent tells the customer the 6-digit verification_code out-of-band.
  4. Customer opens URL, enters code, uploads requested documents.

token is globally unique — it IS the URL slug.  It does not need to be
unguessable (it's in the URL); security comes from the verification_code.
Backend generates token as secrets.token_urlsafe(32) before insert.

verification_code_hash stores a bcrypt hash of the 6-digit code.
Backend generates and hashes the code; it is never stored in plaintext.

deal_id has no FK yet — the deals table ships in the next migration.
A FK constraint will be added in migration 0009.  The column is present
here so document_request items can be linked at deal creation time.

RLS note (see migration 0007):
  The customer-facing public route looks up a document_request by token
  without a tenant context.  Phase 1 uses the 'fh' DB owner role, which
  bypasses RLS.  Phase 2 will harden this with a SECURITY DEFINER function.
  Backend-dev: see TODO in migration 0007 for the full explanation.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, SmallInteger, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from packages.common.db.base import Base, TenantMixin, TimestampMixin, UUIDMixin

from .enums import DocumentRequestStatus

_ev = lambda x: [e.value for e in x]  # noqa: E731


class DocumentRequest(Base, UUIDMixin, TimestampMixin, TenantMixin):
    __tablename__ = "document_requests"

    customer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="CASCADE"),
        nullable=False,
    )

    lead_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("leads.id", ondelete="SET NULL"),
        nullable=True,
    )

    # deal_id: no FK constraint until deals table exists (migration 0009).
    deal_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    instructions: Mapped[str | None] = mapped_column(Text, nullable=True)

    # URL slug — globally unique; generated by backend (secrets.token_urlsafe).
    token: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, index=True
    )

    # Bcrypt hash of the 6-digit verification code.
    verification_code_hash: Mapped[str] = mapped_column(
        String(255), nullable=False
    )

    status: Mapped[DocumentRequestStatus] = mapped_column(
        Enum(DocumentRequestStatus,
             name="document_request_status",
             create_type=False,
             values_callable=_ev),
        nullable=False,
        default=DocumentRequestStatus.PENDING,
        server_default=DocumentRequestStatus.PENDING.value,
    )

    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    # Set when the customer successfully enters the verification code.
    verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Backend enforces a small max (e.g., 5) to throttle brute-force.
    verification_attempts: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, default=0, server_default="0"
    )

    # ON DELETE RESTRICT — must know the creator for audit; prevent orphans.
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )

    # Added in migration 0034
    property_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("properties.id", ondelete="SET NULL"),
        nullable=True,
    )

    agent_note: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ------------------------------------------------------------------
    # Single-use / reactivation columns (added in migration 0037)
    # ------------------------------------------------------------------
    # Set when the customer successfully completes the upload flow.
    # While NOT NULL, the public upload route returns 410 Gone.
    # Cleared (set back to NULL) when an agent/admin reactivates the request.
    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Incremented each time an agent/admin reactivates a closed request.
    # Provides an audit trail for how many times the link was recycled.
    reactivated_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
