"""Media model — public property media stored in Cloudflare R2.

Media is ALWAYS public (CDN-served). Private documents use PrivateDocument.

storage_key is the R2 object key, globally unique. The CDN URL is assembled
by the service layer: {CF_R2_CDN_BASE}/{storage_key}. Never store absolute
CDN URLs in the DB — keys are stable, base URLs may change.

variants holds a map of processed sizes generated by the media worker:
  {"thumb": "public/props/{id}/cover-thumb.webp",
   "medium": "public/props/{id}/cover-medium.webp"}
The worker populates this after initial upload; it starts as NULL.

ordering controls gallery display order. The service layer renumbers on reorder
rather than using fractional indexing, for simplicity in Phase 1.
"""

import uuid

from sqlalchemy import BigInteger, Enum, ForeignKey, Integer, SmallInteger, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from packages.common.db.base import Base, TenantMixin, TimestampMixin, UUIDMixin

from .enums import MediaKind

_ev = lambda x: [e.value for e in x]  # noqa: E731


class Media(Base, UUIDMixin, TimestampMixin, TenantMixin):
    __tablename__ = "media"

    property_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("properties.id", ondelete="CASCADE"),
        nullable=False,
    )

    kind: Mapped[MediaKind] = mapped_column(
        Enum(MediaKind, name="media_kind", create_type=False,
             values_callable=_ev),
        nullable=False,
    )

    # R2 object key — service assembles full CDN URL.
    storage_key: Mapped[str] = mapped_column(String(1024), nullable=False)

    # Populated by media worker after upload; NULL until processed.
    variants: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    mime_type: Mapped[str] = mapped_column(String(128), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)

    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Gallery display order; service renumbers on reorder.
    ordering: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, default=0, server_default="0"
    )

    alt_text: Mapped[str | None] = mapped_column(String(255), nullable=True)

    uploaded_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
