export const AREAS_BY_CITY: Record<string, { value: string; label: string }[]> = {
  "abu-dhabi": [
    { value: "airport-street", label: "Airport Street" },
    { value: "al-bahia", label: "Al Bahia" },
    { value: "al-bateen", label: "Al Bateen" },
    { value: "al-danah", label: "Al Danah" },
    { value: "al-falah-street", label: "Al Falah Street" },
    { value: "al-ghadeer", label: "Al Ghadeer" },
    { value: "al-jubail-island", label: "Al Jubail Island" },
    { value: "al-karamah", label: "Al Karamah" },
    { value: "al-khalidiyah", label: "Al Khalidiyah" },
    { value: "al-khubeirah", label: "Al Khubeirah" },
    { value: "al-manaseer", label: "Al Manaseer" },
    { value: "al-maqtaa", label: "Al Maqtaa" },
    { value: "al-markaziya", label: "Al Markaziya" },
    { value: "al-maryah-island", label: "Al Maryah Island" },
    { value: "al-muntazah", label: "Al Muntazah" },
    { value: "al-muroor", label: "Al Muroor" },
    { value: "al-mushrif", label: "Al Mushrif" },
    { value: "al-nahyan", label: "Al Nahyan" },
    { value: "al-raha-beach", label: "Al Raha Beach" },
    { value: "al-raha-gardens", label: "Al Raha Gardens" },
    { value: "al-rawdah", label: "Al Rawdah" },
    { value: "al-reef", label: "Al Reef" },
    { value: "al-reem-island", label: "Al Reem Island" },
    { value: "al-shamkha", label: "Al Shamkha" },
    { value: "al-zahiyah", label: "Al Zahiyah" },
    { value: "baniyas", label: "Baniyas" },
    { value: "between-two-bridges", label: "Between Two Bridges" },
    { value: "capital-centre", label: "Capital Centre" },
    { value: "corniche-area", label: "Corniche Area" },
    { value: "danet-abu-dhabi", label: "Danet Abu Dhabi" },
    { value: "hamdan-street", label: "Hamdan Street" },
    { value: "hydra-village", label: "Hydra Village" },
    { value: "khalifa-city", label: "Khalifa City" },
    { value: "madinat-zayed", label: "Madinat Zayed" },
    { value: "masdar-city", label: "Masdar City" },
    { value: "mina-zayed", label: "Mina Zayed" },
    { value: "mohamed-bin-zayed-city", label: "Mohamed Bin Zayed City" },
    { value: "mussafah", label: "Mussafah" },
    { value: "rawdhat-abu-dhabi", label: "Rawdhat Abu Dhabi" },
    { value: "saadiyat-island", label: "Saadiyat Island" },
    { value: "shakhbout-city", label: "Shakhbout City" },
    { value: "the-marina", label: "The Marina" },
    { value: "tourist-club-area", label: "Tourist Club Area" },
    { value: "yas-island", label: "Yas Island" },
    { value: "zayed-city", label: "Zayed City" },
    { value: "zayed-sports-city", label: "Zayed Sports City" },
  ],
  ajman: [
    { value: "ain-ajman", label: "Ain Ajman" },
    { value: "ajman-corniche", label: "Ajman Corniche" },
    { value: "ajman-downtown", label: "Ajman Downtown" },
    { value: "ajman-marina", label: "Ajman Marina" },
    { value: "ajman-uptown", label: "Ajman Uptown" },
    { value: "al-alia", label: "Al Alia" },
    { value: "al-amerah", label: "Al Amerah" },
    { value: "al-bahia", label: "Al Bahia" },
    { value: "al-bustan", label: "Al Bustan" },
    { value: "al-hamidiyah", label: "Al Hamidiyah" },
    { value: "al-helio", label: "Al Helio" },
    { value: "al-humaid-city", label: "Al Humaid City" },
    { value: "al-jurf", label: "Al Jurf" },
    { value: "al-mowaihat", label: "Al Mowaihat" },
    { value: "al-nakhil", label: "Al Nakhil" },
    { value: "al-nuaimiya", label: "Al Nuaimiya" },
    { value: "al-rashidiya", label: "Al Rashidiya" },
    { value: "al-rawda", label: "Al Rawda" },
    { value: "al-rumaila", label: "Al Rumaila" },
    { value: "al-sawan", label: "Al Sawan" },
    { value: "al-tallah-1", label: "Al Tallah 1" },
    { value: "al-tallah-2", label: "Al Tallah 2" },
    { value: "al-yasmeen", label: "Al Yasmeen" },
    { value: "al-zahya", label: "Al Zahya" },
    { value: "al-zorah", label: "Al Zorah" },
    { value: "emirates-city", label: "Emirates City" },
    { value: "garden-city", label: "Garden City" },
    { value: "liwara-1", label: "Liwara 1" },
  ],
  "al-ain": [
    { value: "al-bateen", label: "Al Bateen" },
    { value: "al-fou-ah", label: "Al Fou'ah" },
    { value: "al-jahili", label: "Al Jahili" },
    { value: "al-jimi", label: "Al Jimi" },
    { value: "al-khibeesi", label: "Al Khibeesi" },
    { value: "al-maqam", label: "Al Maqam" },
    { value: "al-markhaniyyah", label: "Al Markhaniyyah" },
    { value: "al-mutarad", label: "Al Mutarad" },
    { value: "al-muwaiji", label: "Al Muwaiji" },
    { value: "al-qattara", label: "Al Qattara" },
    { value: "al-rawdah-al-sharqiyah", label: "Al Rawdah Al Sharqiyah" },
    { value: "al-sarouj", label: "Al Sarouj" },
    { value: "al-tiwayya", label: "Al Tiwayya" },
    { value: "asharij", label: "Asharij" },
    { value: "central-district", label: "Central District" },
    { value: "falaj-hazzaa", label: "Falaj Hazzaa" },
    { value: "ghnaymah", label: "Ghnaymah" },
    { value: "hili", label: "Hili" },
    { value: "ni-mah", label: "Ni'mah" },
    { value: "shiab-al-ashkhar", label: "Shiab Al Ashkhar" },
    { value: "sheibat-al-watah", label: "Sheibat Al Watah" },
    { value: "zakhir", label: "Zakhir" },
  ],
  dubai: [
    { value: "al-awir", label: "Al Awir" },
    { value: "al-badaa", label: "Al Badaa" },
    { value: "al-barari", label: "Al Barari" },
    { value: "al-barsha", label: "Al Barsha" },
    { value: "al-furjan", label: "Al Furjan" },
    { value: "al-garhoud", label: "Al Garhoud" },
    { value: "al-jaddaf", label: "Al Jaddaf" },
    { value: "al-karama", label: "Al Karama" },
    { value: "al-khawaneej", label: "Al Khawaneej" },
    { value: "al-mamzar", label: "Al Mamzar" },
    { value: "al-manara", label: "Al Manara" },
    { value: "al-mina", label: "Al Mina" },
    { value: "al-mizhar", label: "Al Mizhar" },
    { value: "al-nahda", label: "Al Nahda" },
    { value: "al-quoz", label: "Al Quoz" },
    { value: "al-qusais", label: "Al Qusais" },
    { value: "al-rashidiya", label: "Al Rashidiya" },
    { value: "al-safa", label: "Al Safa" },
    { value: "al-satwa", label: "Al Satwa" },
    { value: "al-sufouh", label: "Al Sufouh" },
    { value: "al-warqaa", label: "Al Warqaa" },
    { value: "al-wasl", label: "Al Wasl" },
    { value: "arabian-ranches", label: "Arabian Ranches" },
    { value: "arabian-ranches-2", label: "Arabian Ranches 2" },
    { value: "arabian-ranches-3", label: "Arabian Ranches 3" },
    { value: "arjan", label: "Arjan" },
    { value: "barsha-heights", label: "Barsha Heights (Tecom)" },
    { value: "bluewaters-island", label: "Bluewaters Island" },
    { value: "bur-dubai", label: "Bur Dubai" },
    { value: "business-bay", label: "Business Bay" },
    { value: "culture-village", label: "Culture Village" },
    { value: "damac-hills", label: "Damac Hills" },
    { value: "damac-hills-2", label: "Damac Hills 2" },
    { value: "damac-lagoons", label: "Damac Lagoons" },
    { value: "deira", label: "Deira" },
    { value: "difc", label: "DIFC" },
    { value: "discovery-gardens", label: "Discovery Gardens" },
    { value: "downtown-dubai", label: "Downtown Dubai" },
    { value: "dubai-creek-harbour", label: "Dubai Creek Harbour" },
    { value: "dubai-festival-city", label: "Dubai Festival City" },
    { value: "dubai-harbour", label: "Dubai Harbour" },
    { value: "dubai-hills-estate", label: "Dubai Hills Estate" },
    { value: "dubai-internet-city", label: "Dubai Internet City" },
    { value: "dubai-investment-park", label: "Dubai Investment Park" },
    { value: "dubai-islands", label: "Dubai Islands" },
    { value: "dubai-marina", label: "Dubai Marina" },
    { value: "dubai-media-city", label: "Dubai Media City" },
    { value: "dubai-science-park", label: "Dubai Science Park" },
    { value: "dubai-silicon-oasis", label: "Dubai Silicon Oasis" },
    { value: "dubai-south", label: "Dubai South" },
    { value: "dubai-sports-city", label: "Dubai Sports City" },
    { value: "dubai-studio-city", label: "Dubai Studio City" },
    { value: "dubailand", label: "Dubailand" },
    { value: "emirates-hills", label: "Emirates Hills" },
    { value: "expo-city", label: "Expo City" },
    { value: "international-city", label: "International City" },
    { value: "jebel-ali", label: "Jebel Ali" },
    { value: "jlt", label: "Jumeirah Lake Towers" },
    { value: "jbr", label: "Jumeirah Beach Residence" },
    { value: "jvc", label: "Jumeirah Village Circle" },
    { value: "jvt", label: "Jumeirah Village Triangle" },
    { value: "jumeirah", label: "Jumeirah" },
    { value: "jumeirah-golf-estates", label: "Jumeirah Golf Estates" },
    { value: "jumeirah-islands", label: "Jumeirah Islands" },
    { value: "jumeirah-park", label: "Jumeirah Park" },
    { value: "la-mer", label: "La Mer" },
    { value: "meydan", label: "Meydan" },
    { value: "mirdif", label: "Mirdif" },
    { value: "mohammed-bin-rashid-city", label: "Mohammed Bin Rashid City" },
    { value: "motor-city", label: "Motor City" },
    { value: "mudon", label: "Mudon" },
    { value: "nad-al-sheba", label: "Nad Al Sheba" },
    { value: "palm-jumeirah", label: "Palm Jumeirah" },
    { value: "pearl-jumeirah", label: "Pearl Jumeirah" },
    { value: "production-city", label: "Dubai Production City" },
    { value: "ras-al-khor", label: "Ras Al Khor" },
    { value: "reem", label: "Reem" },
    { value: "remraam", label: "Remraam" },
    { value: "serena", label: "Serena" },
    { value: "sheikh-zayed-road", label: "Sheikh Zayed Road" },
    { value: "sobha-hartland", label: "Sobha Hartland" },
    { value: "the-greens", label: "The Greens" },
    { value: "the-lakes", label: "The Lakes" },
    { value: "the-meadows", label: "The Meadows" },
    { value: "the-springs", label: "The Springs" },
    { value: "the-sustainable-city", label: "The Sustainable City" },
    { value: "the-valley", label: "The Valley" },
    { value: "the-views", label: "The Views" },
    { value: "the-villa", label: "The Villa" },
    { value: "tilal-al-ghaf", label: "Tilal Al Ghaf" },
    { value: "town-square", label: "Town Square" },
    { value: "umm-suqeim", label: "Umm Suqeim" },
    { value: "wasl-gate", label: "Wasl Gate" },
    { value: "za-abeel", label: "Za'abeel" },
  ],
  fujairah: [
    { value: "al-dana-island", label: "Al Dana Island" },
    { value: "al-faseel-area", label: "Al Faseel Area" },
    { value: "al-hayl", label: "Al Hayl" },
    { value: "al-mahatta", label: "Al Mahatta" },
    { value: "al-suda", label: "Al Suda" },
    { value: "corniche-al-fujairah", label: "Corniche Al Fujairah" },
    { value: "gurfah-area", label: "Gurfah Area" },
    { value: "hamad-bin-abdullah-road", label: "Hamad Bin Abdullah Road" },
    { value: "merashid-area", label: "Merashid Area" },
    { value: "mina-al-fajer", label: "Mina Al Fajer" },
    { value: "mirbah", label: "Mirbah" },
    { value: "sakamkam", label: "Sakamkam" },
    { value: "town-centre", label: "Town Centre" },
  ],
  "ras-al-khaimah": [
    { value: "al-dhait", label: "Al Dhait" },
    { value: "al-hail", label: "Al Hail" },
    { value: "al-hamra-village", label: "Al Hamra Village" },
    { value: "al-hudaibah", label: "Al Hudaibah" },
    { value: "al-kharran", label: "Al Kharran" },
    { value: "al-mairid", label: "Al Mairid" },
    { value: "al-marjan-island", label: "Al Marjan Island" },
    { value: "al-nakheel", label: "Al Nakheel" },
    { value: "al-qurm", label: "Al Qurm" },
    { value: "al-rams", label: "Al Rams" },
    { value: "al-refaa", label: "Al Refaa" },
    { value: "aljazeera-al-hamra", label: "Aljazeera Al Hamra" },
    { value: "corniche-ras-al-khaimah", label: "Corniche Ras Al Khaimah" },
    { value: "dafan-al-nakheel", label: "Dafan Al Nakheel" },
    { value: "julfar", label: "Julfar" },
    { value: "khuzam", label: "Khuzam" },
    { value: "mina-al-arab", label: "Mina Al Arab" },
    { value: "rak-city", label: "RAK City" },
    { value: "shamal-julphar", label: "Shamal Julphar" },
    { value: "sheikh-khalifa-city", label: "Sheikh Khalifa City" },
    { value: "sheikh-saqr-city", label: "Sheikh Saqr City" },
    { value: "yasmin-village", label: "Yasmin Village" },
  ],
  sharjah: [
    { value: "abu-shagara", label: "Abu Shagara" },
    { value: "al-azra", label: "Al Azra" },
    { value: "al-ghuwair", label: "Al Ghuwair" },
    { value: "al-hamriyah", label: "Al Hamriyah" },
    { value: "al-jazzat", label: "Al Jazzat" },
    { value: "al-jubail", label: "Al Jubail" },
    { value: "al-khan", label: "Al Khan" },
    { value: "al-khaledia-suburb", label: "Al Khaledia Suburb" },
    { value: "al-mahatah", label: "Al Mahatah" },
    { value: "al-majaz", label: "Al Majaz" },
    { value: "al-mamzar", label: "Al Mamzar" },
    { value: "al-manakh", label: "Al Manakh" },
    { value: "al-mujarrah", label: "Al Mujarrah" },
    { value: "al-musalla", label: "Al Musalla" },
    { value: "al-nabba", label: "Al Nabba" },
    { value: "al-nahda-sharjah", label: "Al Nahda (Sharjah)" },
    { value: "al-nasserya", label: "Al Nasserya" },
    { value: "al-qasba", label: "Al Qasba" },
    { value: "al-qasimia", label: "Al Qasimia" },
    { value: "al-qulayaah", label: "Al Qulayaah" },
    { value: "al-rahmaniya", label: "Al Rahmaniya" },
    { value: "al-rifah", label: "Al Rifah" },
    { value: "al-sajaa", label: "Al Sajaa" },
    { value: "al-shahba", label: "Al Shahba" },
    { value: "al-shuwaihean", label: "Al Shuwaihean" },
    { value: "al-soor", label: "Al Soor" },
    { value: "al-tai", label: "Al Tai" },
    { value: "al-taawun", label: "Al Taawun" },
    { value: "al-zahia", label: "Al Zahia" },
    { value: "aljada", label: "Aljada" },
    { value: "bu-tina", label: "Bu Tina" },
    { value: "corniche-al-buhaira", label: "Corniche Al Buhaira" },
    { value: "hoshi", label: "Hoshi" },
    { value: "muwaileh", label: "Muwaileh" },
    { value: "rolla-area", label: "Rolla Area" },
    { value: "sharjah-university-city", label: "Sharjah University City" },
    { value: "tilal-city", label: "Tilal City" },
  ],
  "umm-al-quwain": [
    { value: "al-abraq-1", label: "Al Abraq 1" },
    { value: "al-butain", label: "Al Butain" },
    { value: "al-dar-al-baida", label: "Al Dar Al Baida" },
    { value: "al-haditha", label: "Al Haditha" },
    { value: "al-hawiyah", label: "Al Hawiyah" },
    { value: "al-humrah", label: "Al Humrah" },
    { value: "al-maqtaa", label: "Al Maqtaa" },
    { value: "al-qarayen", label: "Al Qarayen" },
    { value: "al-ramlah", label: "Al Ramlah" },
    { value: "al-rashidiya", label: "Al Rashidiya" },
    { value: "al-rass", label: "Al Rass" },
    { value: "al-raudah", label: "Al Raudah" },
    { value: "al-riqqah", label: "Al Riqqah" },
    { value: "al-salamah", label: "Al Salamah" },
    { value: "al-salam-city", label: "Al Salam City" },
    { value: "falaj-al-mualla", label: "Falaj Al Mualla" },
    { value: "green-belt", label: "Green Belt" },
    { value: "umm-al-quwain-marina", label: "Umm Al Quwain Marina" },
    { value: "umm-al-thuoob", label: "Umm Al Thuoob" },
  ],
};
// KSA city areas are not yet populated — AREAS_BY_CITY[slug] will be undefined (treat as []).
