export const CITIES_BY_COUNTRY: Record<string, { value: string; label: string }[]> = {
  AE: [
    { value: "abu-dhabi", label: "Abu Dhabi" },
    { value: "ajman", label: "Ajman" },
    { value: "al-ain", label: "Al Ain" },
    { value: "dubai", label: "Dubai" },
    { value: "fujairah", label: "Fujairah" },
    { value: "ras-al-khaimah", label: "Ras Al Khaimah" },
    { value: "sharjah", label: "Sharjah" },
    { value: "umm-al-quwain", label: "Umm Al Quwain" },
  ],
  SA: [
    { value: "abha", label: "Abha" },
    { value: "dammam", label: "Dammam" },
    { value: "hail", label: "Hail" },
    { value: "jeddah", label: "Jeddah" },
    { value: "jubail", label: "Jubail" },
    { value: "khobar", label: "Khobar" },
    { value: "mecca", label: "Mecca" },
    { value: "medina", label: "Medina" },
    { value: "riyadh", label: "Riyadh" },
    { value: "tabuk", label: "Tabuk" },
    { value: "taif", label: "Taif" },
    { value: "yanbu", label: "Yanbu" },
  ],
};
