export const CURRENCIES: { value: string; label: string }[] = [
  { value: "AED", label: "AED" },
  { value: "USD", label: "USD" },
  { value: "SAR", label: "SAR" },
  { value: "EUR", label: "EUR" },
  { value: "GBP", label: "GBP" },
  { value: "KWD", label: "KWD" },
  { value: "OMR", label: "OMR" },
  { value: "BHD", label: "BHD" },
  { value: "QAR", label: "QAR" },
];

export const COUNTRIES: { value: string; label: string }[] = [
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "KW", label: "Kuwait" },
  { value: "OM", label: "Oman" },
  { value: "BH", label: "Bahrain" },
  { value: "QA", label: "Qatar" },
  { value: "AU", label: "Australia" },
  { value: "CA", label: "Canada" },
  { value: "DE", label: "Germany" },
  { value: "EG", label: "Egypt" },
  { value: "ES", label: "Spain" },
  { value: "FR", label: "France" },
  { value: "GB", label: "United Kingdom" },
  { value: "IN", label: "India" },
  { value: "IQ", label: "Iraq" },
  { value: "IT", label: "Italy" },
  { value: "JO", label: "Jordan" },
  { value: "KE", label: "Kenya" },
  { value: "LB", label: "Lebanon" },
  { value: "NG", label: "Nigeria" },
  { value: "PH", label: "Philippines" },
  { value: "PK", label: "Pakistan" },
  { value: "SY", label: "Syria" },
  { value: "TR", label: "Turkey" },
  { value: "US", label: "United States" },
  { value: "ZA", label: "South Africa" },
];

export const NATIONALITIES: { value: string; label: string }[] = [
  { value: "AE", label: "Emirati" },
  { value: "SA", label: "Saudi" },
  { value: "KW", label: "Kuwaiti" },
  { value: "OM", label: "Omani" },
  { value: "BH", label: "Bahraini" },
  { value: "QA", label: "Qatari" },
  { value: "AU", label: "Australian" },
  { value: "CA", label: "Canadian" },
  { value: "DE", label: "German" },
  { value: "EG", label: "Egyptian" },
  { value: "ES", label: "Spanish" },
  { value: "FR", label: "French" },
  { value: "GB", label: "British" },
  { value: "IN", label: "Indian" },
  { value: "IQ", label: "Iraqi" },
  { value: "IT", label: "Italian" },
  { value: "JO", label: "Jordanian" },
  { value: "KE", label: "Kenyan" },
  { value: "LB", label: "Lebanese" },
  { value: "NG", label: "Nigerian" },
  { value: "PH", label: "Filipino" },
  { value: "PK", label: "Pakistani" },
  { value: "SY", label: "Syrian" },
  { value: "TR", label: "Turkish" },
  { value: "US", label: "American" },
  { value: "ZA", label: "South African" },
];

export const LANGUAGES: { value: string; label: string }[] = [
  { value: "en", label: "English" },
  { value: "ar", label: "Arabic" },
  { value: "fr", label: "French" },
  { value: "hi", label: "Hindi" },
  { value: "ur", label: "Urdu" },
  { value: "fil", label: "Filipino" },
  { value: "es", label: "Spanish" },
  { value: "de", label: "German" },
];
